### ISSUE TITLE
Select Module error

### ISSUE THREAD

**Issue by FajarWG** [unikom-codelabs/splace-classroom#35]
jadi ketika memilih pilihan yang paling atas, otomatis keselect 2 module, dan itu jadi gk bisa dipilih. bisa dicoba di https://educlassai.unikomcodelabs.id/quiz/generator

akun:
buana
password

![image](https://github.com/user-attachments/assets/cb83c9f8-47f2-4d30-97b8-f9f3ac011201)

**Comment by FajarWG** [comment]
Sekalian yang deadline otomatis isi setelah generate quiz itu blom....
![image](https://github.com/user-attachments/assets/de2a32c4-72e1-415f-92e4-d70afc4fbb52)

**Comment by ichsnn** [comment]
https://github.com/unikom-codelabs/splace-classroom/commit/04df8b8a5e6d5cb1164350d3a7f3d84b2ba69fa3

**Comment by FajarWG** [comment]
nice fix
